name: release website

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js with pnpm
              uses: actions/setup-node@v3
              with:
                node-version: 'latest'
            - run: |
                npm install -g pnpm
                pnpm install

            - name: Install dependencies
              run: pnpm install

            - name: Build
              run: pnpm build